### ISSUE TITLE
`TODO` New features

### ISSUE THREAD

**Issue by AyhamAl-Ali** [SkriptLang/Skript#4185]
### Suggestion

:wave: There are many [new] expressions, conditions and events that can be added to Skript and here are some/most if anyone wants to contribute.

### Notes:
- I will be doing some of them slowly as I can but if someone wants to take over some features please let us know in the comments so others don't work on the same feature.
- Make sure to add a check if method exists since some/most of them are added recently to Minecraft.
- Some of them are only in Paper just something you might need to know :) 

## Entity

- [ ] Entity#getFreezeTicks
- [ ] Entity#getMaxFreezeTicks
- [ ] Entity#setFreezeTicks
- [ ] Entity#isFrozen
- [ ] Entity#setRotation
- [ ] Entity#setPortalCooldown​
- [ ] Entity#setSilent​
- [ ] Entity#setTicksLived​
- [ ] Entity#isTicking
- [ ] Entity#isValid (maybe)
- [ ] Entity#isEmpty
- [ ] Entity#isCustomNameVisible
- [ ] Entity#fromMobSpawner
- [ ] Entity#getMaxFireTicks
- [ ] Entity#getPose + Pose Class

## LivingEntity
- [ ] LivingEntity#setInvisible​
- [ ] LivingEntity#setCanPickupItems
- [ ] LivingEntity#getCanPickupItems
- [ ] LivingEntity#setMaximumNoDamageTicks​
- [ ] LivingEntity#setSwimming
- [ ] LivingEntity#setMaximumAir
- [ ] LivingEntity#setCollidable
- [ ] LivingEntity#isInvisible
- [ ] LivingEntity#isCollidable
- [ ] LivingEntity#isClimbing
- [ ] LivingEntity#getArrowsInBody
- [ ] LivingEntity#setArrowsInBody
- [ ] LivingEntity#getShieldBlockingDelay
- [ ] LivingEntity#setShieldBlockingDelay
- [ ] LivingEntity#getItemUseRemainingTime
- [ ] LivingEntity#getHandRaisedTime
- [ ] LivingEntity#isHandRaised
- [ ] LivingEntity#getHandRaised
- [ ] LivingEntity#isJumping
- [ ] LivingEntity#setJumping
- [ ] LivingEntity#getHurtDirection
- [ ] LivingEntity#setHurtDirection
- [ ] LivingEntity#getActiveItem
- [ ] LivingEntity#setActiveItem
- [ ] LivingEntity#getCategory
- [ ] LivingEntity#getCollidableExemptions
- [ ] LivingEntity#getMaximumAir
- [ ] LivingEntity#setArrowCooldown
- [ ] LivingEntity#getRemoveWhenFarAway
- [ ] LivingEntity#setRemoveWhenFarAway
- [ ] LivingEntity#hasLineOfSight

## Block
- [ ] Block#isPreferredTool
- [ ] Block#getBreakSpeed
- [ ] Block#isBlockFaceIndirectlyPowered
- [ ] Block#isBlockFacePowered

## Events
- [ ] BroadcastMessageEvent​
- [ ] PlayerVelocityEvent
- [ ] TabCompleteEvent

### Why?

In case someone would like to contribute

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this suggestion.

**Comment by AyhamAl-Ali** [comment]
I searched for each method using `Find In Files` feature in Intellij IDE but it seems that this search isn't 100% accurate so if you find any suggestions above that have been done already please let me know.

**Comment by Fusezion** [comment]
Just for cleaning up purposes, some things added that currently aren't listed here as completed
[LivingEntity#setArrowsInBody & LivingEntity#getArrowsInBody](https://docs.skriptlang.org/expressions.html#ExprArrowsStuck)
[Entity#setSilent](https://docs.skriptlang.org/effects.html#EffSilence) + [Entity#isSilent](https://docs.skriptlang.org/conditions.html#CondIsSilent)​
