### ISSUE TITLE
Legacy Code Tracker

### ISSUE THREAD

**Issue by sovdeeth** [SkriptLang/Skript#6641]
### Suggestion

This suggestion will track elements of Skript code that should be removed as we drop support for various Minecraft versions. 
2.8/2.9 supports 1.13+, and 2.10 supports 1.18+, so this issue will have a section for <1.13 legacy code and <1.18 legacy code.

This is by no means comprehensive, I'm mainly tracking the major bits.

I've looked through the files in order up to the ch.njol.skript.entity package.

### Why?

To help keep track of elements of Skript that aren't needed anymore and that can and should be reworked to be simpler and more modern.

### <1.13 Legacy code
- [ ] ItemData: OldItemData and other 1.13 compats
- [ ] BlockCompat: possibly useful to keep around in case of future major change, but I find that unlikely
- [ ] BurgerHelper
- [ ] PassengerUtils
- [ ] BukkitClasses: getEntity(UUID) method check
- [ ] BukkitEventValues: AOE cloud potion data handle
- [ ] Syntaxes that can have checks removed / docs updated:
  - [ ] CondHasResourcePack
  - [ ] CondIgnitionProcess
  - [ ] CondIsFuel
  - [ ] CondIsInteractable
  - [ ] CondIsPassable
  - [ ] CondIsSheared
  - [ ] CondIsSwimming
  - [ ] CondIsUnbreakable
  - [ ] EffExplodeCreeper
  - [ ] EffLoadServerIcon
  - [ ] EffMakeFly
  - [ ] EffPlayerVisibility
  - [ ] EffSendBlockChange
  - [ ] EffSendTitle

### <1.17 Legacy code
- [ ] EntityUtils: Age-related methods can be simplified
- [ ] ItemUtils: isAir() method check
- [ ] PassengerUtils
- [ ] WorldUtils
- [ ] Syntaxes that can have checks removed / docs updated:
  - [ ] CondAnchorWorks
  - [ ] CondEntityIsInLiquid
  - [ ] CondEntityIsWet
  - [ ] CondHasCustomModelData
  - [ ] CondIsClimbing
  - [ ] CondIsInvisible
  - [ ] CondIsJumping
  - [ ] CondIsLeftHanded
  - [ ] CondIsPreferredTool
  - [ ] CondIsWithin
  - [ ] EffApplyBoneMeal
  - [ ] EffCancelItemUse
  - [ ] EffExplodeCreeper
  - [ ] EffHandedness
  - [ ] EffInvisible
  - [ ] EffLook
  - [ ] EffMessage
  - [ ] EffStopSound
  - [ ] EffSwingHand

### Agreement

- [X] I have read the guidelines above and affirm I am following them with this suggestion.

**Comment by cheeezburga** [comment]
I think the PassengerUtils can be checked off, unless I missed something in the merged PR?
